version: 2
updates:
- package-ecosystem: 'github-actions'
  directory: "/"
  schedule:
    interval: daily
    time: '10:00'
    timezone: Japan
  labels:
  - 'CI/CD'
  commit-message:
    prefix: ci

- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: '10:00'
    timezone: Japan
  labels:
  - 'dependencies'
  commit-message:
    prefix: deps
