name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**.md'
  pull_request:
    paths:
      - '**'
      - '!**.md'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: docker-compose build
      - run: make build
      - run: make test
