name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**.md'
  pull_request:
    paths:
      - '**'
      - '!**.md'

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2.3.4
      - run: docker-compose build
      - run: make build
      - run: make test
